configMap:
  name: dados
  data:
    SERVER_HOST: "http://server-0.server:8081/eureka,http://server-1.server:8081/eureka"
    DB_HOST: "alura-foods-app-mysql"
    DB_USER: "root"

gateway:
  replicaCount: 2
  image: bielwolf/java-gateway-k8s:v3
  port: 80

pagamentos:
  replicaCount: 2
  image: bielwolf/java-pagamentos-k8s:v3
  port: 40000

pedidos:
  replicaCount: 2
  image: bielwolf/java-pedidos-k8s:v3
  port: 40001

server:
  replicaCount: 2
  image: bielwolf/java-server-k8s:v3
  port: 8081

services:
  # - name: mysql
  #   label: mysql
  #   port: 3306
  - name: server
    label: server
    port: 8081
  - name: pagamentos-ms
    label: pagamentos
    port: 40000
  - name: pedidos-ms
    label: pedidos
    port: 40001

secret: 
  name: "alura-foods-app-mysql"